### ISSUE TITLE
Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined)

### ISSUE THREAD

**Issue by duclm98** [TabBlazor/TabBlazor#156]
I encountered the following issue:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
      Error: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
          at http://localhost:5039/_framework/blazor.web.js:1:734
          at Array.forEach (<anonymous>)
          at l.findFunction (http://localhost:5039/_framework/blazor.web.js:1:702)
          at b (http://localhost:5039/_framework/blazor.web.js:1:5445)
          at http://localhost:5039/_framework/blazor.web.js:1:3238
          at new Promise (<anonymous>)
          at y.beginInvokeJSFromDotNet (http://localhost:5039/_framework/blazor.web.js:1:3201)
          at Object.ri [as invokeJSJson] (http://localhost:5039/_framework/blazor.web.js:1:165152)
          at http://localhost:5039/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:178364
          at Tl (http://localhost:5039/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:179198)
Microsoft.JSInterop.JSException: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
Error: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
    at http://localhost:5039/_framework/blazor.web.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost:5039/_framework/blazor.web.js:1:702)
    at b (http://localhost:5039/_framework/blazor.web.js:1:5445)
    at http://localhost:5039/_framework/blazor.web.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://localhost:5039/_framework/blazor.web.js:1:3201)
    at Object.ri [as invokeJSJson] (http://localhost:5039/_framework/blazor.web.js:1:165152)
    at http://localhost:5039/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:178364
    at Tl (http://localhost:5039/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:179198)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at TabBlazor.ClickOutside.AddClickOutsideHandler()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Can everyone help me fix it, thanks

**Comment by magahl** [comment]
We are gonna need more then that? 

Whats your setup? How does one reproduce it?
